name: Deploy

on:
  workflow_run:
    workflows: ["Laravel","Lint"]
    types: [completed]

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    runs-on: ubuntu-latest

    steps:
      # Trigger Laravel Forge Deploy
      - uses: jbrooksuk/laravel-forge-action@v1.0.4
        with:
          trigger_url: ${{ secrets.TRIGGER_URL }}
