name: Lint

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM Dependencies and Build
        run: npm install && npm run build

      - name: Lint
        run: npm run lint
